she_codes_news/news/urls.py
from django.urls import path
from django.contrib.auth.models import User
from . import views
from django.views.generic.detail import DetailView


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #loads an individual story using a numerical key
    path('story/<int:pk>/', views.StoryView.as_view(), name='story'),
    #form to add a new story
    path('add-story/', views.AddStoryView.as_view(), name ='newStory'),
    #stories grouped by category considering value in page with list of
    #categories over something like StoryCard
    path('category/<str:pk>/', views.CategoryView.as_view(), name='storyCategory'),
    #stories grouped by author
    #to be considered, an author profile page
    path('author/<slug:slug>/', views.StoriesbyAuthor.as_view(), name='storyAuthor'),
    #list of story categories - to be called by card maybe??
    path('category/', views.NewsListView.as_view(), name='newsList'),
    #list of stories by authors - to be called by card instead?
    path('author/', views.NewsAuthorListView.as_view(), name='authorList'),
    #not working
    # path('story/<int:pk>/edit/', views.EditStory.as_view(), name='editStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #news is the main app, so the blank url will take people straight there
    path('', include('news.urls')),
    #admin site set to default config
    path('admin/', admin.site.urls),
    #will allow users urls & django config
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),



]

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes Mews</title>
        <meta name="description" content="">
        <meta name="author" content="Kiri Mews">
        
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} Mews</h1>
                </a>
            </div>
            {% include './nav.html' %}
        </header>

        {% block content %}
        {% endblock %}

        <footer>
        {% include './footer.html'%}
        </footer>
    </body>
</html>

she_codes_news/templates/footer.html
<div id = "categories">

</div>

<div id = "authors">
    {% for author in all_authors %}
     <a href="{% url 'news:storyAuthor' story.author.username %}"> {{ author.full_name }}</a>
   {% endfor %}
</div>
    <h4>
    {% for category in all_categories %}
        <a href="{% url 'news:storyCategory' category.pk %}">{{ category }}</a></h4>

   {% endfor %}

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if user.is_authenticated %}
        <a href="#"> {{user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
</nav>