she_codes_news/news/urls.py
from django.urls import path
from django.contrib.auth.models import User
from . import views
from django.views.generic.detail import DetailView


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #loads an individual story using a numerical key
    path('story/<int:pk>/', views.StoryView.as_view(), name='story'),
    #form to add a new story
    path('add-story/', views.AddStoryView.as_view(), name ='newStory'),
    #stories grouped by category considering value in page with list of
    #categories over something like StoryCard
    path('category/<str:pk>/', views.CategoryView.as_view(), name='storyCategory'),
    #stories grouped by author
    #to be considered, an author profile page
    path('author/<slug:slug>/', views.StoriesbyAuthor.as_view(), name='storyAuthor'),
    #list of story categories - to be called by card maybe??
    path('category/', views.NewsListView.as_view(), name='newsList'),
    #list of stories by authors - to be called by card instead?
    path('author/', views.NewsAuthorListView.as_view(), name='authorList'),
    #not working
    # path('story/<int:pk>/edit/', views.EditStory.as_view(), name='editStory'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #news is the main app, so the blank url will take people straight there
    path('', include('news.urls')),
    #admin site set to default config
    path('admin/', admin.site.urls),
    #will allow users urls & django config
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),



]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

"""
Things to Remember when adding or updating models!
Add Model - makemigrations/migrate
Add Views - Import if needed
Add URLS - Import if needed
Update Admin Page - Import if needed
Add Template
Update existing Templates
Consider Forms
"""

class NewsCategory (models.Model):
#Categories have been defined with their name as pk.
#Duplicates will now be alloed, and SuperUsers can add additional Categories behind the by logging in.
    category = models.CharField(max_length=50, unique=True, primary_key=True)
    """verbose name & verbose plural name act as display names, 
    providing formatting when called by forms, or in the admin center 
    """
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category


    
class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    """related_name is what this model is called when
    referred to from the other model
    """
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name = "stories"
    )
    pub_date = models.DateField(verbose_name = 'Date Publised')
    content = models.TextField()
    image_url = models.URLField(max_length = 200, verbose_name = 'Image URL')
    category = models.ForeignKey(
        NewsCategory,
        on_delete = models.CASCADE,
        related_name = "stories",
        # Can allow null for existing data - but require it on form.
        null = True,
        verbose_name = 'Category',

    )
    """verbose name & verbose plural name act as display names, 
    providing formatting when called by forms, or in the admin center 
    """
    class Meta:
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

"""
Story form configued to allow front-end upload & updates of NewsStory
To be developed - editing and deleting interface.
"""

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'category', 'content', 'author']
        widgets = {
            'image_url': forms.URLField,
            'pub_date': forms.DateInput(
                format=('%m/%d/%y'),
                attrs={ 
                    'class': 'form-control',
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            )
        }


# class EditStoryForm(ModelForm):
#     class Meta:
#         model = NewsStory
#         fields = ['title', 'pub_date', 'category', 'content', 'image_url', 'author']
#         widgets = {
#             'image_url': forms.URLField,
#             'pub_date': forms.DateInput(
#                 format=('%m/%d/%y'),
#                 attrs={ 
#                     'class': 'form-control',
#                     'placeholder': 'Select a date',
#                     'type': 'date'
#                 }
#             )
#         }

she_codes_news/news/views.py
from django.contrib.auth import get_user_model
from django.views import generic
from django.views.generic import DetailView, UpdateView, ListView, CreateView  
from django.urls import reverse_lazy
from .models import NewsStory, NewsCategory
from .forms import StoryForm
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import UserPassesTestMixin


User = get_user_model()

"""News 'home' page"""
class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.order_by('-pub_date')[4:6]
    
        return context

"""view for individual story page"""
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = "news/story.html"
    context_object_name = "story"


"""View to post a new story"""
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
        


# """View to edit post"""
# class EditStory(generic.UpdateView):
#     form_class = EditStoryForm
#     model = NewsStory
#     context_object_name = 'storyForm'
#     template_name = 'news/editStory.html'
#     success_url = reverse_lazy('news:index')

#     # def form_valid(self, form):
#     #     author=self.request.user
#     #     form.instance.author = self.request.user
#     #     return super().form_valid(form)
#     # return False

#     def is_author(self,user):
#         author = self.request.user
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)
#     def test_func(self):
#             story = self.get_object()
#             if self.request.user == story.author:
#                 return True

        





"""Context Object name is used to call in templates"""

class StoriesbyAuthor(generic.DetailView):
    model = User
    template_name = 'news/storyAuthor.html'
    context_object_name = 'author_name'
    slug_field = "username"
    #set slug here #then change url to use string #change all url code in templates to use 

class CategoryView(generic.DetailView):
    #This view returns all stories, but allows for filtering by the NewsCategory Class
    model = NewsCategory
    template_name = 'news/storyCategory.html'
    context_object_name = 'category_name'



"""View to show list of posts"""
class NewsListView(ListView):
    template_name = "news/categoryList.html"

    def get_queryset(self):
        '''Return all news categories.'''
        return NewsCategory.objects.all(), User.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_categories'] = NewsCategory.objects.order_by('category')
        context['all_authors'] = User.objects.order_by('last_name')
        return context

class NewsAuthorListView(ListView):
    template_name = "news/authorList.html"

    def get_queryset(self):
        '''Return all news categories.'''
        return NewsCategory.objects.all(), User.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_stories'] = NewsStory.objects.order_by('-pub_date')
        context['all_authors'] = User.objects.order_by('last_name')
        return context

she_codes_news/news/templates/news/authorList.html
{% comment %}Will consider adding/inserting this as a page

Need to figure out slug before trying to update{% endcomment %}
{% block content %}

<div class="title">Authors:</div>
 
 <div>
        {% for author in all_authors %}
            <a href="{% url 'news:storyAuthor' story.author.username %}">{{ story.author.first_name }}</a>
            

   {% endfor %}

 </div>
{% endblock %}

she_codes_news/news/templates/news/categoryList.html
{% comment %}Will consider adding/inserting this as a page{% endcomment %}
{% block content %}

<div class="title">Categories:</div>
 
 <div>
        {% for category in all_categories %}
            <a href="{% url 'news:storyCategory' category.pk %}">{{ category }}</a></h4>

   {% endfor %}

 </div>
{% endblock %}



<div id = "categories">

</div>

<div id = "authors">  
</div>
    <h4>
    {% for category in all_categories %}
        <a href="{% url 'news:storyCategory' category.pk %}">{{ category }}</a></h4>

   {% endfor %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"> 
{% endblock %}
{% comment %} Need to work on formatting of login button {% endcomment %}
{% block content%}

<div id ="wrapper">

{% if user.is_authenticated %}
<form action="" method="post">
    <div id = "create-story">
    <h2>Tell us your story!</h2></div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
    {% else %}
    <br>
    <div class="title"><h2><a href="{% url 'login' %}">Login</a></h4></div>
    {% endif %}
</form>
</div>
{% endblock %}

she_codes_news/news/templates/news/editStory.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"> 
{% endblock %}

{% block content%}

<div id ="wrapper">


{% if user.is_authenticated %}
<form action="" method="post">
    <div id = "create-story">
    <h2>Tell us your story!</h2></div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
    {% else %}
    <br>
    <div class="title"><h2><a href="{% url 'login' %}">Login</a></h4></div>
    {% endif %}
</form>
</div>
{% endblock %}

she_codes_news/news/templates/news/index.html
   {% extends "base.html" %}
   {% load static %}
   {% block stylesheets %}
   <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"> 
   {% endblock %}
   {% block content %}
   <div class="title">
   <h2>Here's the latest!</h2>
   </div>
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
    <div id = "ad">
    <a href = "https://www.petcircle.com.au/">
    <img src = "https://images.unsplash.com/photo-1532303517831-241791b20fb9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80">
        <div class="story-card-text">
            <h3>Your cat is hungry</h3>
            <h4>Buy them some Wet Food</h4>
            <p>Pooping rainbow while flying in a toasted bread costume in space cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers and make plans to dominate world and then take a nap the fat cat sat on the mat bat away with paws lick butt. Hiss and stare at nothing then run suddenly away sit in window and stare oooh, a bird, yum and get video posted to internet for chasing red dot and try to hold own back foot to clean it but foot reflexively kicks you in face, </p>
            <strong>
            <h4># hungrycats #ad</h4>
            </strong>
    </div>
    </a>
    </div>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
            {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    {% endblock %}

she_codes_news/news/templates/news/largeStoryCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id%}">

            <img src = "{{ story.image_url }}">
        
        <div class="story-card-text">
            <h3>{{ story.title|truncatechars:35 }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
            <p>{{story.content|truncatechars:150 }}</p>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"> 
{% endblock %}
{% block content %}

<p>
<div id ="story-header">
    <div class="title"><h2>{{ story.title }}</h2></div>
        <!-- CSS needs to be updated for space on Author -->

    <div id="author"><h4>Story by:&nbsp;<a href="{% url 'news:storyAuthor' story.author.username %}">{{ story.author }}</a></h4></div>
    </p>
    </div>
<div id="story-wrapper">
    <em>Published: {{ story.pub_date }}</em>
    <div id="story-content">
        <img src = "{{ story.image_url }}">
        {{ story.content|linebreaks }}
    </div>

    <div id = "see-link"><h4>See more stories about&nbsp;<a href="{% url 'news:storyCategory' story.category.pk %}"> {{ story.category }}</a></h4>
    </div>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyAuthor.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"> 
{% endblock %}
#It is important to start a new block here
{% block content %}

<div class="title">
<h2> Stories by {{ author_name }} </h2>
</div>

 <div id="all-stories">
    <div id = "ad-card">
    <a href = "https://www.cathaven.com.au/">
    <img src = "https://images.pexels.com/photos/127027/pexels-photo-127027.jpeg?cs=srgb&dl=pexels-vadim-b-127027.jpg&fm=jpg">
        <div class="story-card-text">
            <h3>Being a cat is hard</h3>
            <h4>We write stories for you - pls give monies</h4>
            <p>Pooping rainbow while flying in a toasted bread costume in space cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers and make plans to dominate world and then take a nap the fat cat sat on the mat bat away with paws lick butt. Hiss and stare at nothing then run suddenly away sit in window and stare oooh, a bird, yum and get video posted to internet for chasing red dot and try to hold own back foot to clean it but foot reflexively kicks you in face, </p>
            <strong>
            <h4>#donate</h4>
            </strong>
    </div>
    </a>
    </div>

<br>
   {% for story in author_name.stories.all %}
      {% include "./largeStoryCard.html" with story=story %}
   {% endfor %}
 </div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id%}">
        {% if position < 5 %}
            <img src = "{{ story.image_url }}">
        {% else %}
            <img src = "{{ story.image_url }}">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
            
        </div>
    </a>
</div>

she_codes_news/news/templates/news/storyCategory.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"> 
{% endblock %}
#It is important to start a new block here
{% block content %}



<div class="title">
<h2> Stories about {{ category_name }} </h2>
</div>

 <div id="all-stories">
    <div id = "ad-card">
    <a href = "https://www.cathaven.com.au/">
    <img src = "https://images.unsplash.com/photo-1596789866050-b7d8cf68c636?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80">
        <div class="story-card-text">
            <h3>Pls give money</h3>
            <h4>We will write more stories about {{ category_name }}</h4>
            <p>Pooping rainbow while flying in a toasted bread costume in space cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers and make plans to dominate world and then take a nap the fat cat sat on the mat bat away with paws lick butt. Hiss and stare at nothing then run suddenly away sit in window and stare oooh, a bird, yum and get video posted to internet for chasing red dot and try to hold own back foot to clean it but foot reflexively kicks you in face, </p>
            <strong>
            <h4>#donate</h4>
            </strong>
    </div>
    </a>
    </div>

<br>
   {% for story in category_name.stories.all %}
      {% include "./largeStoryCard.html" with story=story %}
      



   {% endfor %}
 </div>
{% endblock %}